extraction:
  cpp:
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DUSE_CUDA=OFF ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
